import assert from "assert/strict";
import { readFileSync } from "fs";
import test from "node:test";
import { parse as parseYaml } from "yaml";

const sources = parseYaml(readFileSync("sources.yaml", "utf-8"));
const marketplace = JSON.parse(
  readFileSync(".claude-plugin/marketplace.json", "utf-8"),
);
const agents = readFileSync("AGENTS.md", "utf-8");

test("marketplace entries match the source manifest", () => {
  const expectedPlugins = sources.skills.map((skill) => ({
    name: skill.name,
    description: skill.description,
    source: `./${skill.target.path}`,
    category: skill.target.category,
    author: {
      name: skill.author.name,
      github: skill.author.github,
    },
  }));

  assert.deepEqual(marketplace.plugins, expectedPlugins);
  assert.equal(marketplace.metadata.skill_count, sources.skills.length);
});

test("keeps the generated footer separate from maintainer notes", () => {
  const footer = "Generated by n-skills sync.";

  assert.equal(agents.split(footer).length - 1, 1);
  assert.doesNotMatch(agents, /---Generated by n-skills sync\./u);
});
